config/routes.rb
CdnControl::Application.routes.draw do
  root :to => "libraries#index"
  devise_for :users
  resources :users do
    member do
      put 'set_roles'
    end
  end
  resources :libraries
  match '/terms_of_use' => 'home#terms_of_use'
  match '/about_this_service' => 'home#about_this_service'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    elsif user.is_author?
      can :read, :all
      can :manage, Library, :user => user
      can :manage, User, :id => user.id
      cannot :set_role, User
    else
      can :read, :all
      can :manage, User, :id => user.id
      cannot :set_role, User
    end
  end
end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :description, :name, :versions_attributes, :uris_attributes
  validates_presence_of :name, :on => :create, :message => "can't be blank"
  validates_uniqueness_of :name, :on => :create, :message => "must be unique"
  validates_format_of :name, :with => /^[-_a-z\d]+$/, :message => "is not formatted correctly"
  belongs_to :user
  has_many :versions, :dependent => :destroy
  accepts_nested_attributes_for :versions, :reject_if => lambda { |a| a[:version].blank? }, :allow_destroy => true
  attr_reader :keywords
  def keywords
    "#{name} #{description.gsub(/<[^>]+>/,'').gsub(/[\r\n]+/, ' ')} #{user.name}".split(/[\s[[:punct:]]]+/).uniq.join(' ')
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/uri.rb
class Uri < ActiveRecord::Base
  belongs_to :version
  attr_accessor :replace
  attr_accessible :file_name, :file_uid, :file, :make_link, :replace
  file_accessor :file do
    storage_path{|f| "#{file_storage_path}/#{f.name}"}
  end
  def file_storage_path
    "#{version.library.name}/#{version.version}"
  end
  after_create :unpack
  before_destroy :invalidate
  def unpack
    if self.file_name.downcase.match(/\.zip$/)
      #source = File.join("#{Rails.root}/public/system/dragonfly/#{Rails.env}",file_uid)
      zipfile = Zip::ZipFile.open(file.path)
      zipfile.each do |entry|
        if entry.file? && ! File.basename(entry.name).match(/^\./)
          if entry.name.downcase.match(/\.(gif|jpeg|jpg|png|js|css)$/)
            extracted_file = zipfile.read(entry.name)
            new_uri = self.version.uris.build
            new_uri.file = extracted_file
            new_uri.file_name = File.basename(entry.name)
            new_uri.save!
          end
        end
      end
      self.destroy
    end
  end
  def invalidate
    conn = Fog::CDN.new(
      :provider => 'AWS',
      :aws_access_key_id => AWS_ACCESS_KEY,
      :aws_secret_access_key => AWS_SECRET_KEY
    )
    conn.post_invalidation AWS_DISTRIBUTION_ID, '/' + self.file_uid
    Rails.logger.info 'Trying to delete the file'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :libraries, :dependent => :destroy
  rolify
  
  def is_admin?
    has_role? :admin
  end
  
  def is_author?
    has_role? :author
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
  attr_accessible :library, :version, :uris_attributes
  belongs_to :library
  has_many :uris, :dependent => :destroy
  accepts_nested_attributes_for :uris, :reject_if => lambda { |a| a[:file].blank? && a[:file_name].blank? && a[:make_link].blank? }, :allow_destroy => true
  default_scope order('id DESC')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource
  def index
    @libraries = Library.order(:name)
  end
  def show
    @library = Library.find(params[:id])
  end
  def new
    @library = current_user.libraries.build
  end
  def create
    @library = current_user.libraries.build(params[:library])
    if(@library.save)
      redirect_to @library, :notice => 'Library created'
    else
      render :action => 'new'
    end
  end
  def edit
    #@library = current_user.libraries.find(params[:id])
  end
  def update
    #@library = current_user.libraries.find(params[:id])
    if @library.update_attributes(params[:library])
      redirect_to @library, :notice  => "Updated library"
    else
      render :action => 'edit'
    end
  end
  def destroy
    @library = current_user.libraries.find(params[:id])
    @library.destroy
    redirect_to libraries_url, :notice => 'Library deleted'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def set_roles
    @user = User.find(params[:id])
    params[:user_roles].each do |key, val|
      if val == 'yes'
        @user.add_role(key.to_sym)
      else 
        if(@user.has_role?(key.to_sym))
          @user.revoke(key.to_sym)
        end
      end
    end
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/uris_helper.rb
module UrisHelper
  def link(uri, style = nil)
    if(style == 'secure')
      protocol = 'https://'
      host = 'dnk2vbhoq39rr.cloudfront.net/'
    else
      host = 'cdn.freewaypro.com/'
      protocol = 'http://'
    end
    link = "#{protocol}#{host}#{uri.file_uid}";
    if uri.make_link?
      link_to(link, link)
    else
      link
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def role_checkboxes(user)
    out = ''
    eval(ENV["ROLES"]).each do |role|
      out += content_tag(:label, :class => 'checkbox') do
        "#{hidden_field_tag('user_roles[' + role + ']', '')}#{check_box_tag('user_roles[' + role + ']', 'yes', user.roles.map(&:name).include?(role))} #{role.titleize}&nbsp;&nbsp;".html_safe
      end
    end
    out.html_safe
  end
end

app/views/home/about_this_service.html.erb
<%= content_for :title, 'About this Service' %>
<div class="row">
  <div class="span7">
    <h1>About this Service</h1>
    <p class="lead">This is the FreewayPro CDN, a service for Freeway Action authors to make their software simpler and faster.</p>
    <h4>So what is this thing?</h4>

    <p>This site uploads any file a member decides to share with the world into the Amazon CloudFront CDN (content delivery network). Files hosted in this manner are available to people everywhere in the world in a very efficient fashion. Rather than waiting for a request to bounce its way from Taipei to London and back with the goods, that request gets routed to the geographically-closest server in a worldwide net of edge cache hosts. Even at the speed of light, physical distance does matter.</p>

    <h4>What should I host here?</h4>

    <p>If you write Freeway Actions that add JavaScript to the page, it’s a good idea to externalize your scripts to make the page head easier to look at and to make it easier for search engines to read. Take that a step further, and if the script never changes (likely, if it’s library code) then there’s no reason for your Action to have to carry it around, write it out, create a file, etc. It’s much simpler to create a single-line link to that file from a public server.</p>

    <p>Your Actions may also provide CSS or refer to images that don’t ever change. Those are also great candidates for this service.</p>

    <h4>How to use it in your Actions</h4>

    <blockquote>
      <p class="lead">“&#8230;you’ll need to have this fish in your ear&#8230;” </p>
    </blockquote>

    <p>Seriously, though, you need the following two functions somewhere in your action-javascript:</p>

    <script src="https://gist.github.com/4522045.js"></script>

    <p>And then you call it thus, with the link to your CDN-hosted script as the second argument:</p>

    <script src="https://gist.github.com/4524952.js"></script>

    <p>No matter where you do that in the publishing cycle, there will only be one such link in the page head when all (cooperating) Actions are done with their work. If you are concerned with older “Scripty” Actions being in the same page, then it is advisable to call this function from within the <code>fwAfterEndHTML()</code> callback, though.</p>

    <p>Cooperating in this scheme has taken a turn for the better, too. Unlike the previous iteration of the “Scripty” club, there is no need for each Action to follow the same precepts in order to guarantee that all the needed Scriptaculous libraries are loaded, or for all Actions to announce themselves to one another. As long as each Action on the page inserts its script links using <code>fwAdd()</code> instead of <code>fwAddRaw()</code>, the <code>pageHasLinkToScript()</code> function can find them and modify them or avoid duplicating them as needed.</p>
  </div>
  <div id="terms_of_use" class="span4 well pull-right">
    <h2>Terms of Use</h2>
    <p>Welcome to the FreewayPro CDN (also referred to below as the Service).</p>
    <p>By using this Service, you agree to the following terms. If you don&rsquo;t agree, there are other places where you can host your content.</p>
    <p>This Service is offered free of charge to the <a href="http://softpress.com">Freeway Pro</a> community, for the benefit of Action authors and other like-minded Web craftspeople, by <a href="http://walterdavisstudio.com">Walter Davis Studio</a>.</p>
    <p>Any content you post here will be replicated across the global Internet in a relatively short period of time, and it will be difficult but not impossible to remove it from public view. Please consider that before posting those launch codes...</p>
    <ol>
      <li>All content posted on this Service must comply with U.S. copyright law. If it isn&rsquo;t your work or property, you must have permission to post it here for all the world to see.</li>
      <li>We claim no intellectual property rights over the material you provide to the Service. Any materials uploaded remain yours.</li>
      <li>We do not pre-screen content, but Walter Davis Studio and its designees have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Service.</li>
      <li>This service depends on the Amazon global network, which we do not own or control. Any disruption in the Amazon US/East network center could make it impossible to manage your content within this service. Any content already propagated to the globally-distributed CloudFront service should remain available, although that is by no means guaranteed either.</li>
    </ol>
    <p class="lead">This Service is provided without charge, and without any guarantee or warrantee that it will always remain on-line or that it will be useful for any purpose. Under no circumstances will Walter Davis Studio or its designees be liable for any loss or damages, financial or otherwise, under any theory or principle of legal responsibility of any sort. If you rely on this Service, that is your own decision.</p>
    <address>
      <strong>Walter Davis Studio</strong><br />
      7530 Mountain Avenue<br />
      Melrose Park, PA 19027
    </address>
    <p>Updated: <time datetime="2013-01-13">January 13, 2013</time></p>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home</h1>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/home/terms_of_use.html.erb
<%= content_for :title, 'Terms of Use' %>
<h1>Terms of Use</h1>
<p class="lead">Welcome to the FreewayPro CDN (also referred to below as the Service).</p>
<p>By using this Service, you agree to the following terms. If you don&rsquo;t agree, there are other places where you can host your content.</p>
<p>This Service is offered free of charge to the <a href="http://softpress.com">Freeway Pro</a> community, for the benefit of Action authors and other like-minded Web craftspeople, by <a href="http://walterdavisstudio.com">Walter Davis Studio</a>.</p>
<p>Any content you post here will be replicated across the global Internet in a relatively short period of time, and it will be difficult but not impossible to remove it from public view. Please consider that before posting those launch codes...</p>
<ol>
  <li>All content posted on this Service must comply with U.S. copyright law. If it isn&rsquo;t your work or property, you must have permission to post it here for all the world to see.</li>
  <li>We claim no intellectual property rights over the material you provide to the Service. Any materials uploaded remain yours.</li>
  <li>We do not pre-screen content, but Walter Davis Studio and its designees have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Service.</li>
</ol>
<p>This Service is provided without charge, and without any guarantee or warrantee that it will always remain on-line or that it will be useful for any purpose. Under no circumstances will Walter Davis Studio or its designees be liable for any loss or damages, financial or otherwise, under any theory or principle of legal responsibility of any sort. If you rely on this Service, that is your own decision.</p>
<address>
  <strong>Walter Davis Studio</strong><br />
  7530 Mountain Avenue<br />
  Melrose Park, PA 19027
</address>
<p><time datetime="2013-01-11">January 11, 2013</time></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "FreewayPro CDN", root_path, :class => 'brand' %>
<ul class="nav main">
  <li>
    <%= link_to 'Libraries', libraries_path %>
  </li>
  <li>
    <%= link_to 'About this Service', '/about_this_service' %>
  </li>
</ul>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Log in', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "#{yield(:title)} | FreewayPro CDN" : "FreewayPro CDN" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cdn Control" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
      <footer>
        <p>
          Copyright &copy;2013 <a href="http://walterdavisstudio.com/" title="Walter Davis Studio">Walter Davis Studio</a>. All rights reserved.<br />
          <a href="/about_this_service">Terms of Use</a>
        </p>
      </footer>
    </div> <!--! end of #main -->
  </body>
</html>

app/views/libraries/_form.html.erb
<script type="text/javascript">
  function decorate_file_button(elm){
    var fileName;
    fileName = $(elm).val();

    // Remove any previous file names
    $(elm).parent().next('.file-input-name').remove();
    if (!!$(elm).prop('files') && $(elm).prop('files').length > 1) {
      fileName = $(elm)[0].files.length+' files';
      //$(this).parent().after('<span class="file-input-name">'+$(this)[0].files.length+' files</span>');
    }
    else {
      // var fakepath = 'C:\\fakepath\\';
      // fileName = $(this).val().replace('C:\\fakepath\\','');
      fileName = fileName.substring(fileName.lastIndexOf('\\')+1,fileName.length);
    }

    $(elm).parent().after('<span class="file-input-name">'+fileName+'</span>');
    
  }
</script>
<%= nested_form_for @library, :html => {:multipart => true} do |f| %>
<% if @library.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

    <ul>
    <% @library.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<span class="hint">(lower-case letters, numbers, hyphens, or underscores only)</span>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_area :description, :rows => 6 %>
</p>
<h2>Versions <%= f.link_to_add '<i class="icon-folder-open"></i>'.html_safe + " Add a version", :versions, :class => "btn btn-small" %></h2>
<%= f.fields_for :versions %>
<hr class="flat"/>
<p>
<%= f.submit({:class => 'btn btn-primary'}) %>
<%= link_to 'Cancel', libraries_path, :class => 'btn' %>
&nbsp;
<%= link_to( 'Delete', @library, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' ) if @library.persisted? %>
</p>
<%- end -%>
<script type="text/javascript">
$(document).ready(function(){
  $('input[type=file]').bootstrapFileInput();
});
</script>

app/views/libraries/_uri_fields.html.erb
<p class="form-inline text-left">
<%- if f.object.file_name? -%>
  <i class="icon-file" style="opacity: 0.4"></i>
  <%= f.object.file_name %> &nbsp;
<%- end -%>
<%= f.label :make_link, f.check_box(:make_link) + ' Make link', :class => 'checkbox', :style => 'margin-right: 8px' %>
<a class="file-input-wrapper btn btn-small file">Browse
<%= f.file_field :file, :class => 'file', :style => "left: -228px; top: 4px;", :onchange => 'decorate_file_button(this)' %>
</a>
<%- if f.object.file_name? -%>
<%= f.link_to_remove '<span class="close btn-danger btn btn-small" style="float: none">&times;</span>'.html_safe %>
<%- end -%>
<!-- <span class="hint">(upload a Zip to create multiple files in one step)</span> -->
<%# f.label :make_link, f.check_box(:make_link) + ' Make link', :class => 'checkbox' %>
<%# end %>
</p>

app/views/libraries/_version_fields.html.erb
<hr class="flat"/>
<p class="form-inline">
<%= f.label :version %>
<%= f.text_field :version, :class => 'input-small' %>
</p>
<p><%= f.link_to_add '<i class="icon-file"></i>'.html_safe + " Add a file to this version", :uris, :class => "btn btn-small" %></p>
<%= f.fields_for :uris %>

app/views/libraries/edit.html.erb
<%= content_for :title, @library.name %>
<h1><%= @library.name %></h1>
<%= render :partial => 'form' %>

app/views/libraries/index.html.erb
<%= content_for :title, 'Libraries' %>
<div class="hero-unit">
  <h1 style="padding-bottom: 14px"><nobr>It’s Open. <wbr/><small>The new FreewayPro CDN.</small></nobr></h1>
  <p>
    This collection of library scripts is hosted at the Amazon CloudFront service for worldwide availability.<br/>
    Sign up for a free account to add your own scripts here, and reference them in your Freeway Actions.
  </p>
  <p><%= link_to( 'Sign Up', new_user_registration_path, :class => 'btn btn-large btn-success' ) %></p>
</div>
<h2>All Libraries</h2>
<form style="overflow: hidden; margin: 0 0 8px;" action="" id="live_search">
  <input type="search" class="search-query pull-left" id="q" placeholder="Live search..." />
  <button id="clear" class="close pull-left" style="margin-left: 8px">&times;</button>
  <%= link_to( 'Create a Library', new_library_path, :class => 'btn pull-right' ) %>
</form>
<p class="nav pull-right"></p>
<table class = "table table-striped table-bordered">
  <thead>
    <tr>
      <th>Library</th>
      <th>Description</th>
      <th>Author</th>
      <th>Latest version</th>
    </tr>
  </thead>
  <tbody>
    <% @libraries.each do |library| %>
    <tr class="lib" data-keyword="<%= library.keywords %>">
      <td><%= link_to library.name, library %></td>
      <td><%= library.description.squish.truncate(60) %></td>
      <td><%= library.user.name %></td>
      <td><%= library.versions.first.try :version %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/libraries/new.html.erb
<%= content_for :title, 'New Library' %>
<h1>New Library</h1>
<%= render :partial => 'form' %>

app/views/libraries/show.html.erb
<%= content_for :title, @library.name %>
<h1><%= @library.name %></h1>
<%= simple_format @library.description %>
<%= render @library.versions.order('id DESC') %>
<p><%= link_to 'All Libraries', libraries_path, :class => 'btn' %> <%= link_to 'Edit', edit_library_path(@library), :class => 'btn btn-inverse' %></p>

app/views/users/index.html.erb
<%= content_for :title, 'Members' %>
<h1>Members</h1>
<table class="table table-striped users">
  <tr>
    <th>Name</th>
    <th>Member since</th>
    <th>Roles</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.created_at.to_date %></td>
      <td>
        <%= form_tag( set_roles_user_path(user), {:class => 'form-inline', :style => 'margin-bottom: 0', :method => :put, :onclick => "this.submit()"}) do |f| %>
          <%= role_checkboxes(user) %>
        <%- end -%>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<%= content_for :title, @user.name %>
<h1><%= @user.name %></h1>
  
<p>Email: <%= @user.email if @user.email %></p>
<h2>Libraries:</h2>
<ul>
  <%- @user.libraries.order(:name).each do |library| -%>
  <li><%= link_to library.name, library %></li>
  <%- end -%>
</ul>

app/views/versions/_version.html.erb
<h3><%= version.version %></h3>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>URI</th>
      <th>Secure URI (HTTPS)</th>
    </tr>
  </thead>
  <tbody>
    <%- version.uris.each do |uri| -%>
    <tr>
      <td><%= uri.file_name %></td>
      <td><%= link(uri) %></td>
      <td><%= link(uri, 'secure') %></td>
    </tr>
    <%- end -%>
  </tbody>
</table>
<dt></dt>
<dd></dd>
</dl>